katana_arm_velocity_controller1:
  type: "effort_controllers/JointVelocityController"
  joint: katana_motor1_pan_joint
  pid: {p: 300.0, d: 40.0, i: 0.01}
katana_arm_velocity_controller2:
  type: "effort_controllers/JointVelocityController"
  joint: katana_motor2_lift_joint
  pid: {p: 300.0, d: 30.0, i: 0.01}
katana_arm_velocity_controller3:
  type: "effort_controllers/JointVelocityController"
  joint: katana_motor3_lift_joint
  pid: {p: 300.0, d: 30.0, i: 0.01}
katana_arm_velocity_controller4:
  type: "effort_controllers/JointVelocityController"
  joint: katana_motor4_lift_joint
  pid: {p: 200.0, d: 20.0, i: 0.01}
katana_arm_velocity_controller5:
  type: "effort_controllers/JointVelocityController"
  joint: katana_motor5_wrist_roll_joint
  pid: {p: 100.0, d: 0.05, i: 0.005}
