<?xml version="1.0"?>
<robot name="al5d" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find al5d_description)/urdf/transmissions.urdf.xacro"/>

    <xacro:property name="M_PI" value="3.14159"/>

    <xacro:property name="base_height" value="0.02" />
    <xacro:property name="base_radius" value="0.048" />
    <xacro:property name="upper_base_height" value="0.0702" />
    <xacro:property name="upper_arm_offset" value="0.006" />
    <xacro:property name="upper_arm_length" value="0.14605" />
    <xacro:property name="upper_arm_width" value="0.05" />
    <xacro:property name="lower_arm_length" value="0.187325" />
    <xacro:property name="lower_arm_width" value="0.035" />
    <xacro:property name="wrist_length" value="0.034" />
    <xacro:property name="gripper_length" value="${gripper_height + finger_length/2}" />
    <xacro:property name="wrist_width" value="0.025" />
    <xacro:property name="gripper_width" value="0.05" />
    <xacro:property name="gripper_height" value="0.021" />
    <!-- <xacro:property name="gripper_height" value="0.01" /> -->
    <xacro:property name="finger_length" value="0.04" />
    <xacro:property name="point" value="0.003" />

    <xacro:property name="axis_length" value="0.03" />
    <xacro:property name="axis_width" value="0.001" />

    <xacro:property name="inertia_block">
      <inertial>
        <mass value="0.3"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </xacro:property>

    <link name="world"></link>
    <link name="base">
      <visual>
        <!-- <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry> -->
        <geometry>
          <mesh filename="package://al5d_description/mesh/base/Base.STL"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
      </collision>
      <xacro:insert_block name="inertia_block" />
    </link>
    <link name="upper_base">
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/upper_base/Waist - HS805BB-1.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/upper_base/Waist - Turntable-1.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <collision>
	       <origin xyz="0 0 ${(upper_base_height - base_height - 0.02)/2 + base_height + 0.02}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${upper_base_height - base_height - 0.02}" radius="${base_radius}"/>
        </geometry>
      </collision>
      <xacro:insert_block name="inertia_block" />
    </link>
    <link name="upper_arm">
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/upper_arm/UpperArm - Bracket-1.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/upper_arm/UpperArm - Bracket-2.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${upper_arm_length} ${upper_arm_width} ${upper_arm_width}"/>
        </geometry>
      </collision>
      <xacro:insert_block name="inertia_block" />
    </link>
    <link name="lower_arm">
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/lower_arm/LowerArm - HS422-1.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/lower_arm/LowerArm - HS805BB-1.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/lower_arm/LowerArm - Rod-1.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <!-- <visual>
        <origin xyz="${lower_arm_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${lower_arm_length} ${lower_arm_width} ${lower_arm_width}"/>
        </geometry>
      </visual> -->
      <collision>
        <origin xyz="${lower_arm_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${lower_arm_length} ${lower_arm_width} ${lower_arm_width}"/>
        </geometry>
      </collision>
      <xacro:insert_block name="inertia_block" />
    </link>
    <link name="wrist">
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/wrist/WristLink.STL"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 0.85"/>
        </material>
      </visual>
      <!-- <visual>
        <origin xyz="${wrist_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${wrist_length} ${wrist_width} ${wrist_width}"/>
        </geometry>
      </visual> -->
      <collision>
        <origin xyz="${wrist_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${wrist_length} ${wrist_width} ${wrist_width}"/>
        </geometry>
      </collision>
      <xacro:insert_block name="inertia_block" />
    </link>
    <link name="gripper_base">
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/gripper_base/Gripper - WristTurn-1.STL"/>
        </geometry>
      </visual>
      <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/gripper_base/Gripper - GripperBase-1.STL"/>
        </geometry>
      </visual>
      <!-- <visual>
	      <origin xyz="${gripper_height/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_height} ${gripper_height} ${gripper_width}"/>
        </geometry>
      </visual> -->
      <collision>
        <origin xyz="${gripper_width/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_height} ${gripper_height} ${gripper_width}"/>
        </geometry>
      </collision>
      <xacro:insert_block name="inertia_block" />
    </link>
    <link name="gripper_rightfinger">
      <visual>
        <origin xyz="${gripper_width/4} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_width/2} ${gripper_height} ${gripper_height/4}"/>
        </geometry>
      </visual>
      <!-- <visual>
        <origin xyz="${gripper_width/2} 0 0" rpy="0 0 0"/>
        <geometry>
		      <box size="${gripper_width} ${gripper_height} ${gripper_height}"/>
        </geometry>
      </visual> -->
      <collision>
        <origin xyz="${gripper_width/4} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_width/2} ${gripper_height} ${gripper_height/4}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>
    <link name="gripper_leftfinger">
      <!-- <visual>
        <geometry>
          <mesh filename="package://al5d_description/mesh/left_finger/LeftFinger.STL"/>
        </geometry>
      </visual> -->
      <visual>
        <origin xyz="${gripper_width/4} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_width/2} ${gripper_height} ${gripper_height/4}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${gripper_width/4} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_width/2} ${gripper_height} ${gripper_height/4}"/>
        </geometry>
        <!-- <origin xyz="${gripper_width/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${gripper_width} ${gripper_height} ${gripper_height}"/>
        </geometry> -->
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>
    <link name="end">
      <!-- <visual>
        <geometry>
          <sphere radius=".001" />
        </geometry>
      </visual> -->
    </link>
    <link name="xaxis">
      <visual>
        <origin xyz="${axis_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${axis_length} ${axis_width} ${axis_width}"/>
        </geometry>
      </visual>
    </link>
    <link name="yaxis">
      <visual>
        <origin xyz="0 ${axis_length/2} 0" rpy="0 0 0"/>
        <geometry>
          <box size="${axis_width} ${axis_length} ${axis_width}"/>
        </geometry>
      </visual>
    </link>
    <link name="zaxis">
      <visual>
        <origin xyz="0 0 ${axis_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${axis_width} ${axis_width} ${axis_length}"/>
        </geometry>
      </visual>
    </link>






    <!-- joints -->
    <joint name="base" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="world"/>
      <child link="base"/>
    </joint>
    <joint name="base_rotate" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="base"/>
      <child link="upper_base"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.4" upper="1.4" effort="10" velocity="3.67"/>
    </joint>
    <joint name="shoulder_tilt" type="revolute">
      <origin xyz="0 0 ${upper_arm_offset + upper_base_height}" rpy="${M_PI/2} -${M_PI/2} 0 "/>
      <parent link="upper_base"/>
      <child link="upper_arm"/>
      <axis xyz="0 0 -1"/>
      <limit lower="-1.2" upper="1.4" effort="10" velocity="3.32"/>
    </joint>
    <joint name="elbow_tilt" type="revolute">
      <origin xyz="${upper_arm_length} 0 0" rpy="0 0 -${M_PI/2}" />
      <parent link="upper_arm"/>
      <child link="lower_arm"/>
      <axis xyz="0 0 -1"/>
      <limit lower="-1.8" upper="1.7" effort="10" velocity="3.67"/>
    </joint>
    <joint name="wrist_tilt" type="revolute">
      <origin xyz="${lower_arm_length} 0 0" rpy="0 0 0"/>
      <parent link="lower_arm"/>
      <child link="wrist"/>
      <axis xyz="0 0 -1"/>
      <limit lower="-1.9" upper="1.7" effort="10" velocity="6.98"/>
    </joint>
    <joint name="wrist_rotate" type="revolute">
      <origin xyz="${wrist_length} 0 0" rpy="${M_PI/2} 0 0"/>
      <parent link="wrist"/>
      <child link="gripper_base"/>
      <axis xyz="1 0 0"/>
      <limit lower="-2" upper="1.5" effort="10" velocity="6.98"/>
    </joint>
    <joint name="open_gripperright" type="prismatic">
      <origin xyz="${gripper_height} 0 0.023" rpy="0 0 0"/>
      <origin xyz="${gripper_height} 0 0" rpy="0 0 0"/>
      <parent link="gripper_base"/>
      <child link="gripper_rightfinger"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.03" upper="0.0" effort="100" velocity="6.98"/>
    </joint>
    <joint name="open_gripperleft" type="prismatic">
      <origin xyz="${gripper_height} 0 -0.023" rpy="0 0 0"/>
      <parent link="gripper_base"/>
      <child link="gripper_leftfinger"/>
      <axis xyz="0 0 1"/>
      <limit lower="0" upper="0.03" effort="100" velocity="6.98"/>
    </joint>
    <joint name="end" type="fixed">
      <origin xyz="${wrist_length} 0 0" rpy="0 ${M_PI/2} 0"/>
      <parent link="gripper_base"/>
      <child link="end"/>
    </joint>
    <joint name="axis1" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="end"/>
      <child link="xaxis"/>
    </joint>
    <joint name="axis2" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="end"/>
      <child link="yaxis"/>
    </joint>
    <joint name="axis3" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="end"/>
      <child link="zaxis"/>
    </joint>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <gazebo reference="base">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>true</turnGravityOff>
    <!-- <self_collide>1</self_collide> -->
  </gazebo>
  <gazebo reference="upper_base">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>
  <gazebo reference="upper_arm">
    <turnGravityOff>true</turnGravityOff>
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="lower_arm">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>
  <gazebo reference="wrist">
    <turnGravityOff>true</turnGravityOff>
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="gripper_base">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>
  <gazebo reference="gripper_leftfinger">
    <turnGravityOff>true</turnGravityOff>
    <material>Gazebo/DarkGrey</material>
    <self_collide>1</self_collide>
  </gazebo>
  <gazebo reference="gripper_rightfinger">
    <turnGravityOff>true</turnGravityOff>
    <material>Gazebo/DarkGrey</material>
    <self_collide>1</self_collide>
  </gazebo>
  <gazebo reference="end">
    <turnGravityOff>true</turnGravityOff>
  </gazebo>
  <gazebo reference="xaxis">
    <material>Gazebo/RedTransparentOverlay</material>
    <turnGravityOff>true</turnGravityOff>
  </gazebo>
  <gazebo reference="yaxis">
    <material>Gazebo/GreenTransparentOverlay</material>
    <turnGravityOff>true</turnGravityOff>
  </gazebo>
  <gazebo reference="zaxis">
    <material>Gazebo/BlueTransparentOverlay</material>
    <turnGravityOff>true</turnGravityOff>
  </gazebo>



</robot>
